#version: "3.8"
name: jack
services:

  supagres:
    image: supabase/postgres
    container_name: supagres
    hostname: supagres
    restart: always
    ports:
      - 5430:5432
    environment:
      POSTGRES_HOST: 0.0.0.0
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - supagres:/var/lib/postgresql/data
    networks:
      - jack

  blank_space:
    build: .
    command: python run.py
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - SECRET_KEY=${SECRET_KEY}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_VERBOSE=${LOG_VERBOSE}
      - LOG_FILES=${LOG_FILES}
      - ZERO_TRUST=${ZERO_TRUST}
    depends_on:
      - supagres
    ports:
      - "5000:5000"
    networks:
      - jack


networks:
  jack:

volumes:
  postgres:
  supagres:


